apiVersion: v1
kind: Service
metadata:
  name: backend-fast-food-service
spec:
  selector:
    app: backend-fast-food
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
